[package]
name = "account"
version = "0.2.1"
edition = "2021"
authors = ["Ellemes <3llemes@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.26"